CREATE TABLE IF NOT EXISTS group_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  group_post_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  body TEXT,
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (group_post_id) REFERENCES group_posts(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);