name: Standup Bot for Discord
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate_report:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - name: Fetch open issues
        uses: actions/github-script@v6
        id: fetch-issues
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            if (issues.length === 0) {
              return '**📅 Standup Report**\nNo pending issues today! 🎉';
            }

            // Format for Discord (uses \n for newlines)
            const report = issues.map(issue => {
            const labels = issue.labels.map(label => `\`${label.name}\``).join(', ');
            return `• **${issue.title}** (#${issue.number}) - Labels: ${labels}`;
            }).join('\n');

            return `**📅 Standup Report**\n${report}`;


      - name: Send to Discord
        uses: Ilshidur/action-discord@master
        with:
          args: |
            ${{ steps.fetch-issues.outputs.result }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CHECKUP }}